/**
 * Indobase Design — built-in template library.
 *
 * These are Fabric.js `canvas.toJSON()` documents. Authoring templates as plain JSON is the whole
 * reason this engine replaced the Penpot fork: Penpot's `.penpot` files are binary/zip archives with
 * strict internal schemas that cannot be hand-authored or generated, so its gallery could only ever
 * point at someone else's design files. Here a template is data we own — which also makes AI drafting
 * ("describe your post") and business-data merge (real products/prices into a design) possible later.
 *
 * India-first on purpose: festival sales, WhatsApp status, menu cards and GST-friendly invoicing
 * layouts are where Canva's library is thinnest, so this is where a small set is actually
 * differentiated rather than a worse copy of Canva's thousands.
 *
 * Fonts are Google Fonts already preloaded by index.html (no licensing cost, and the Indic families
 * matter for the Indian market).
 */

type FabricObject = Record<string, unknown>

const FONT_DISPLAY = 'Montserrat'
const FONT_BODY = 'Inter'
const FONT_SERIF = 'Playfair Display'

/** Fabric defaults that every object needs but which are noisy to repeat. */
function rect(o: {
  left: number
  top: number
  width: number
  height: number
  fill: string
  rx?: number
  opacity?: number
}): FabricObject {
  return {
    type: 'Rect',
    version: '6.0.0',
    originX: 'left',
    originY: 'top',
    rx: o.rx ?? 0,
    ry: o.rx ?? 0,
    opacity: o.opacity ?? 1,
    strokeWidth: 0,
    ...o,
  }
}

function circle(o: { left: number; top: number; radius: number; fill: string; opacity?: number }): FabricObject {
  return {
    type: 'Circle',
    version: '6.0.0',
    originX: 'left',
    originY: 'top',
    opacity: o.opacity ?? 1,
    strokeWidth: 0,
    ...o,
  }
}

function text(o: {
  text: string
  left: number
  top: number
  width: number
  fontSize: number
  fill: string
  fontFamily?: string
  fontWeight?: string | number
  textAlign?: string
  lineHeight?: number
  charSpacing?: number
}): FabricObject {
  return {
    type: 'Textbox',
    version: '6.0.0',
    originX: 'left',
    originY: 'top',
    fontFamily: o.fontFamily ?? FONT_BODY,
    fontWeight: o.fontWeight ?? 'normal',
    textAlign: o.textAlign ?? 'left',
    lineHeight: o.lineHeight ?? 1.16,
    charSpacing: o.charSpacing ?? 0,
    splitByGrapheme: false,
    strokeWidth: 0,
    ...o,
  }
}

function doc(background: string, objects: FabricObject[]) {
  return { version: '6.0.0', background, objects }
}

export type SeedTemplate = {
  slug: string
  name: string
  category: string
  width: number
  height: number
  sortOrder: number
  canvas: ReturnType<typeof doc>
}

export const BUILTIN_TEMPLATES: SeedTemplate[] = [
  // ── Social ────────────────────────────────────────────────────────────────────────────────────
  {
    slug: 'festival-sale-post',
    name: 'Festival Sale — Post',
    category: 'social',
    width: 1080,
    height: 1080,
    sortOrder: 10,
    canvas: doc('#3B1E54', [
      circle({ left: -140, top: -140, radius: 260, fill: '#F5A524', opacity: 0.22 }),
      circle({ left: 820, top: 760, radius: 300, fill: '#E8618C', opacity: 0.2 }),
      text({
        text: 'FESTIVAL SALE',
        left: 90,
        top: 250,
        width: 900,
        fontSize: 92,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 900,
        charSpacing: 40,
      }),
      rect({ left: 90, top: 380, width: 180, height: 8, fill: '#F5A524', rx: 4 }),
      text({
        text: 'UP TO 50% OFF',
        left: 90,
        top: 440,
        width: 900,
        fontSize: 130,
        fill: '#F5A524',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        lineHeight: 1.05,
      }),
      text({
        text: 'On all products · Limited period offer',
        left: 90,
        top: 720,
        width: 900,
        fontSize: 38,
        fill: '#E9E2F2',
      }),
      rect({ left: 90, top: 850, width: 430, height: 96, fill: '#F5A524', rx: 48 }),
      text({
        text: 'Shop Now',
        left: 90,
        top: 878,
        width: 430,
        fontSize: 40,
        fill: '#3B1E54',
        fontFamily: FONT_DISPLAY,
        fontWeight: 700,
        textAlign: 'center',
      }),
    ]),
  },
  {
    slug: 'new-arrival-post',
    name: 'New Arrival — Post',
    category: 'social',
    width: 1080,
    height: 1080,
    sortOrder: 20,
    canvas: doc('#F7F3EC', [
      rect({ left: 60, top: 60, width: 960, height: 960, fill: '#FFFFFF', rx: 28 }),
      rect({ left: 120, top: 120, width: 840, height: 470, fill: '#E4DCCF', rx: 20 }),
      text({
        text: 'Add your product photo here',
        left: 120,
        top: 335,
        width: 840,
        fontSize: 30,
        fill: '#9C907C',
        textAlign: 'center',
      }),
      text({
        text: 'NEW ARRIVAL',
        left: 120,
        top: 640,
        width: 840,
        fontSize: 30,
        fill: '#B08549',
        fontWeight: 700,
        charSpacing: 120,
      }),
      text({
        text: 'Your product name',
        left: 120,
        top: 700,
        width: 840,
        fontSize: 78,
        fill: '#2A2118',
        fontFamily: FONT_SERIF,
        fontWeight: 700,
      }),
      text({
        text: '₹1,499  ·  Free delivery',
        left: 120,
        top: 820,
        width: 840,
        fontSize: 40,
        fill: '#6C6152',
      }),
    ]),
  },
  {
    slug: 'discount-story',
    name: 'Discount — Story',
    category: 'story',
    width: 1080,
    height: 1920,
    sortOrder: 30,
    canvas: doc('#0F766E', [
      circle({ left: 640, top: -180, radius: 340, fill: '#5EEAD4', opacity: 0.25 }),
      circle({ left: -220, top: 1480, radius: 380, fill: '#14B8A6', opacity: 0.35 }),
      text({
        text: 'TODAY ONLY',
        left: 100,
        top: 560,
        width: 880,
        fontSize: 46,
        fill: '#99F6E4',
        fontWeight: 700,
        charSpacing: 120,
      }),
      text({
        text: 'FLAT\n30% OFF',
        left: 100,
        top: 660,
        width: 880,
        fontSize: 170,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 900,
        lineHeight: 1.02,
      }),
      text({
        text: 'Use code SAVE30 at checkout',
        left: 100,
        top: 1080,
        width: 880,
        fontSize: 40,
        fill: '#CCFBF1',
      }),
      rect({ left: 100, top: 1240, width: 520, height: 110, fill: '#FFFFFF', rx: 55 }),
      text({
        text: 'Order on WhatsApp',
        left: 100,
        top: 1274,
        width: 520,
        fontSize: 38,
        fill: '#0F766E',
        fontWeight: 700,
        textAlign: 'center',
      }),
    ]),
  },
  {
    slug: 'whatsapp-status-offer',
    name: 'WhatsApp Status — Offer',
    category: 'story',
    width: 1080,
    height: 1920,
    sortOrder: 40,
    canvas: doc('#111827', [
      rect({ left: 0, top: 0, width: 1080, height: 620, fill: '#22C55E', opacity: 0.14 }),
      text({
        text: 'Special offer',
        left: 90,
        top: 700,
        width: 900,
        fontSize: 44,
        fill: '#4ADE80',
        fontWeight: 600,
        charSpacing: 60,
      }),
      text({
        text: 'Buy 1\nGet 1 Free',
        left: 90,
        top: 790,
        width: 900,
        fontSize: 140,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        lineHeight: 1.05,
      }),
      rect({ left: 90, top: 1170, width: 240, height: 6, fill: '#22C55E', rx: 3 }),
      text({
        text: 'Message us to order\n+91 00000 00000',
        left: 90,
        top: 1240,
        width: 900,
        fontSize: 44,
        fill: '#D1FAE5',
        lineHeight: 1.4,
      }),
    ]),
  },
  // ── Print ─────────────────────────────────────────────────────────────────────────────────────
  {
    slug: 'menu-card',
    name: 'Menu Card — A4',
    category: 'print',
    width: 1240,
    height: 1754,
    sortOrder: 50,
    canvas: doc('#FFFBF2', [
      rect({ left: 70, top: 70, width: 1100, height: 1614, fill: '#FFFFFF', rx: 8 }),
      text({
        text: 'MENU',
        left: 120,
        top: 150,
        width: 1000,
        fontSize: 96,
        fill: '#1F2937',
        fontFamily: FONT_SERIF,
        fontWeight: 700,
        textAlign: 'center',
        charSpacing: 120,
      }),
      rect({ left: 520, top: 290, width: 200, height: 4, fill: '#C2925A', rx: 2 }),
      text({
        text: 'Starters',
        left: 140,
        top: 380,
        width: 960,
        fontSize: 46,
        fill: '#C2925A',
        fontFamily: FONT_SERIF,
        fontWeight: 700,
      }),
      text({
        text: 'Paneer Tikka\nVeg Spring Roll\nMasala Papad',
        left: 140,
        top: 460,
        width: 700,
        fontSize: 38,
        fill: '#374151',
        lineHeight: 1.9,
      }),
      text({
        text: '₹220\n₹180\n₹90',
        left: 900,
        top: 460,
        width: 200,
        fontSize: 38,
        fill: '#374151',
        textAlign: 'right',
        lineHeight: 1.9,
      }),
      text({
        text: 'Main Course',
        left: 140,
        top: 760,
        width: 960,
        fontSize: 46,
        fill: '#C2925A',
        fontFamily: FONT_SERIF,
        fontWeight: 700,
      }),
      text({
        text: 'Dal Makhani\nPaneer Butter Masala\nVeg Biryani',
        left: 140,
        top: 840,
        width: 700,
        fontSize: 38,
        fill: '#374151',
        lineHeight: 1.9,
      }),
      text({
        text: '₹280\n₹340\n₹300',
        left: 900,
        top: 840,
        width: 200,
        fontSize: 38,
        fill: '#374151',
        textAlign: 'right',
        lineHeight: 1.9,
      }),
      text({
        text: 'Your restaurant name  ·  +91 00000 00000',
        left: 140,
        top: 1560,
        width: 960,
        fontSize: 30,
        fill: '#9CA3AF',
        textAlign: 'center',
      }),
    ]),
  },
  {
    slug: 'sale-flyer',
    name: 'Sale Flyer — Poster',
    category: 'print',
    width: 1080,
    height: 1350,
    sortOrder: 60,
    canvas: doc('#1D4ED8', [
      rect({ left: 0, top: 980, width: 1080, height: 370, fill: '#FFFFFF' }),
      text({
        text: 'GRAND\nOPENING',
        left: 80,
        top: 220,
        width: 920,
        fontSize: 150,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 900,
        lineHeight: 1.02,
      }),
      rect({ left: 80, top: 600, width: 560, height: 90, fill: '#FBBF24', rx: 45 }),
      text({
        text: 'Everything 40% off',
        left: 80,
        top: 626,
        width: 560,
        fontSize: 38,
        fill: '#1F2937',
        fontWeight: 700,
        textAlign: 'center',
      }),
      text({
        text: 'Visit us this weekend',
        left: 80,
        top: 760,
        width: 920,
        fontSize: 42,
        fill: '#DBEAFE',
      }),
      text({
        text: 'Your Business Name',
        left: 80,
        top: 1060,
        width: 920,
        fontSize: 56,
        fill: '#1D4ED8',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      text({
        text: 'Shop address, city  ·  +91 00000 00000',
        left: 80,
        top: 1150,
        width: 920,
        fontSize: 32,
        fill: '#4B5563',
      }),
    ]),
  },
  {
    slug: 'business-card',
    name: 'Business Card',
    category: 'print',
    width: 1050,
    height: 600,
    sortOrder: 70,
    canvas: doc('#FFFFFF', [
      rect({ left: 0, top: 0, width: 26, height: 600, fill: '#3B8FD6' }),
      text({
        text: 'Your Name',
        left: 90,
        top: 170,
        width: 700,
        fontSize: 62,
        fill: '#111827',
        fontFamily: FONT_DISPLAY,
        fontWeight: 700,
      }),
      text({
        text: 'Founder · Your Business',
        left: 92,
        top: 250,
        width: 700,
        fontSize: 30,
        fill: '#3B8FD6',
        fontWeight: 600,
        charSpacing: 40,
      }),
      rect({ left: 92, top: 320, width: 120, height: 4, fill: '#E5E7EB', rx: 2 }),
      text({
        text: '+91 00000 00000\nhello@yourbusiness.in\nyourbusiness.in',
        left: 92,
        top: 370,
        width: 700,
        fontSize: 26,
        fill: '#6B7280',
        lineHeight: 1.7,
      }),
    ]),
  },
  // ── Presentation ──────────────────────────────────────────────────────────────────────────────
  {
    slug: 'presentation-title',
    name: 'Presentation — Title 16:9',
    category: 'presentation',
    width: 1920,
    height: 1080,
    sortOrder: 80,
    canvas: doc('#0B1220', [
      circle({ left: 1450, top: -220, radius: 420, fill: '#3B8FD6', opacity: 0.18 }),
      rect({ left: 160, top: 380, width: 110, height: 10, fill: '#3B8FD6', rx: 5 }),
      text({
        text: 'Your presentation title',
        left: 160,
        top: 440,
        width: 1300,
        fontSize: 116,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        lineHeight: 1.1,
      }),
      text({
        text: 'Subtitle or short description goes here',
        left: 160,
        top: 700,
        width: 1200,
        fontSize: 44,
        fill: '#94A3B8',
      }),
      text({
        text: 'Your Business  ·  2026',
        left: 160,
        top: 900,
        width: 800,
        fontSize: 30,
        fill: '#64748B',
        charSpacing: 60,
      }),
    ]),
  },
  // ── Ads ───────────────────────────────────────────────────────────────────────────────────────
  {
    slug: 'instagram-ad-product',
    name: 'Instagram Ad — Product',
    category: 'ads',
    width: 1080,
    height: 1080,
    sortOrder: 90,
    canvas: doc('#FFFFFF', [
      rect({ left: 0, top: 0, width: 1080, height: 620, fill: '#EEF2FF' }),
      text({
        text: 'Add product photo',
        left: 80,
        top: 280,
        width: 920,
        fontSize: 28,
        fill: '#94A3B8',
        textAlign: 'center',
      }),
      text({
        text: '{{product_name}}',
        left: 80,
        top: 680,
        width: 920,
        fontSize: 64,
        fill: '#0F172A',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      text({
        text: '{{price}}  ·  Free shipping',
        left: 80,
        top: 780,
        width: 920,
        fontSize: 36,
        fill: '#3B8FD6',
        fontWeight: 700,
      }),
      rect({ left: 80, top: 900, width: 360, height: 88, fill: '#3B8FD6', rx: 44 }),
      text({
        text: 'Shop now',
        left: 80,
        top: 924,
        width: 360,
        fontSize: 32,
        fill: '#FFFFFF',
        fontWeight: 700,
        textAlign: 'center',
      }),
    ]),
  },
  {
    slug: 'facebook-ad-landscape',
    name: 'Facebook Ad — Landscape',
    category: 'ads',
    width: 1200,
    height: 628,
    sortOrder: 100,
    canvas: doc('#0F172A', [
      circle({ left: 900, top: -120, radius: 280, fill: '#3B8FD6', opacity: 0.35 }),
      text({
        text: 'GROW FASTER',
        left: 70,
        top: 160,
        width: 700,
        fontSize: 28,
        fill: '#F5A524',
        fontWeight: 700,
        charSpacing: 80,
      }),
      text({
        text: '{{headline}}',
        left: 70,
        top: 220,
        width: 780,
        fontSize: 64,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      text({
        text: '{{offer}}',
        left: 70,
        top: 420,
        width: 700,
        fontSize: 30,
        fill: '#94A3B8',
      }),
    ]),
  },
  {
    slug: 'linkedin-promo-square',
    name: 'LinkedIn Promo — Square',
    category: 'social',
    width: 1080,
    height: 1080,
    sortOrder: 110,
    canvas: doc('#F8FAFC', [
      rect({ left: 60, top: 60, width: 960, height: 960, fill: '#FFFFFF', rx: 24 }),
      rect({ left: 60, top: 60, width: 960, height: 16, fill: '#0A66C2', rx: 0 }),
      text({
        text: 'CASE STUDY',
        left: 120,
        top: 160,
        width: 840,
        fontSize: 26,
        fill: '#0A66C2',
        fontWeight: 700,
        charSpacing: 100,
      }),
      text({
        text: '{{company_name}}\nincreased leads by 3×',
        left: 120,
        top: 240,
        width: 840,
        fontSize: 64,
        fill: '#0F172A',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        lineHeight: 1.15,
      }),
      text({
        text: 'Built on Indobase — auth, database, and marketing in one place.',
        left: 120,
        top: 560,
        width: 840,
        fontSize: 32,
        fill: '#64748B',
      }),
      text({
        text: 'Learn more →',
        left: 120,
        top: 860,
        width: 400,
        fontSize: 30,
        fill: '#0A66C2',
        fontWeight: 700,
      }),
    ]),
  },
  {
    slug: 'youtube-thumbnail',
    name: 'YouTube Thumbnail',
    category: 'social',
    width: 1280,
    height: 720,
    sortOrder: 120,
    canvas: doc('#111827', [
      rect({ left: 0, top: 0, width: 480, height: 720, fill: '#F5A524' }),
      text({
        text: 'WATCH',
        left: 60,
        top: 280,
        width: 360,
        fontSize: 48,
        fill: '#111827',
        fontFamily: FONT_DISPLAY,
        fontWeight: 900,
        textAlign: 'center',
      }),
      text({
        text: '{{title}}',
        left: 540,
        top: 220,
        width: 680,
        fontSize: 72,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        lineHeight: 1.1,
      }),
      text({
        text: '{{channel}}',
        left: 540,
        top: 520,
        width: 680,
        fontSize: 32,
        fill: '#F5A524',
        fontWeight: 600,
      }),
    ]),
  },
  {
    slug: 'reel-promo',
    name: 'Reel / Shorts Promo',
    category: 'story',
    width: 1080,
    height: 1920,
    sortOrder: 130,
    canvas: doc('#7C3AED', [
      circle({ left: -200, top: 200, radius: 360, fill: '#A78BFA', opacity: 0.35 }),
      text({
        text: 'POV',
        left: 100,
        top: 520,
        width: 880,
        fontSize: 48,
        fill: '#EDE9FE',
        fontWeight: 700,
        charSpacing: 160,
      }),
      text({
        text: '{{hook}}',
        left: 100,
        top: 620,
        width: 880,
        fontSize: 96,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 900,
        lineHeight: 1.05,
      }),
      rect({ left: 100, top: 1200, width: 480, height: 100, fill: '#FFFFFF', rx: 50 }),
      text({
        text: 'Follow for more',
        left: 100,
        top: 1230,
        width: 480,
        fontSize: 34,
        fill: '#7C3AED',
        fontWeight: 700,
        textAlign: 'center',
      }),
    ]),
  },
  {
    slug: 'presentation-agenda',
    name: 'Presentation — Agenda 16:9',
    category: 'presentation',
    width: 1920,
    height: 1080,
    sortOrder: 140,
    canvas: doc('#FFFFFF', [
      rect({ left: 0, top: 0, width: 28, height: 1080, fill: '#3B8FD6' }),
      text({
        text: 'Agenda',
        left: 120,
        top: 120,
        width: 800,
        fontSize: 72,
        fill: '#0F172A',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      text({
        text: '01  {{item_1}}\n02  {{item_2}}\n03  {{item_3}}\n04  {{item_4}}',
        left: 120,
        top: 320,
        width: 1400,
        fontSize: 48,
        fill: '#334155',
        lineHeight: 1.7,
      }),
    ]),
  },
  {
    slug: 'presentation-quote',
    name: 'Presentation — Quote 16:9',
    category: 'presentation',
    width: 1920,
    height: 1080,
    sortOrder: 150,
    canvas: doc('#0B1220', [
      text({
        text: '“',
        left: 160,
        top: 180,
        width: 200,
        fontSize: 220,
        fill: '#3B8FD6',
        fontFamily: FONT_SERIF,
        fontWeight: 700,
      }),
      text({
        text: '{{quote}}',
        left: 200,
        top: 360,
        width: 1500,
        fontSize: 56,
        fill: '#F8FAFC',
        fontFamily: FONT_SERIF,
        lineHeight: 1.35,
      }),
      text({
        text: '— {{attribution}}',
        left: 200,
        top: 820,
        width: 1000,
        fontSize: 32,
        fill: '#94A3B8',
      }),
    ]),
  },
  {
    slug: 'price-list-poster',
    name: 'Price List — Poster',
    category: 'print',
    width: 1080,
    height: 1350,
    sortOrder: 160,
    canvas: doc('#FFF7ED', [
      text({
        text: 'PRICE LIST',
        left: 80,
        top: 100,
        width: 920,
        fontSize: 64,
        fill: '#9A3412',
        fontFamily: FONT_DISPLAY,
        fontWeight: 900,
        textAlign: 'center',
        charSpacing: 80,
      }),
      text({
        text: '{{business_name}}',
        left: 80,
        top: 200,
        width: 920,
        fontSize: 36,
        fill: '#C2410C',
        textAlign: 'center',
      }),
      text({
        text: '{{item_1}}                    {{price_1}}\n{{item_2}}                    {{price_2}}\n{{item_3}}                    {{price_3}}\n{{item_4}}                    {{price_4}}',
        left: 120,
        top: 380,
        width: 840,
        fontSize: 40,
        fill: '#431407',
        lineHeight: 2,
      }),
      text({
        text: 'GST included · Prices in ₹',
        left: 80,
        top: 1180,
        width: 920,
        fontSize: 28,
        fill: '#9A3412',
        textAlign: 'center',
      }),
    ]),
  },
  {
    slug: 'gst-invoice-header',
    name: 'GST Invoice Header',
    category: 'print',
    width: 1240,
    height: 1754,
    sortOrder: 170,
    canvas: doc('#FFFFFF', [
      rect({ left: 0, top: 0, width: 1240, height: 180, fill: '#0F172A' }),
      text({
        text: '{{business_name}}',
        left: 80,
        top: 55,
        width: 700,
        fontSize: 44,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      text({
        text: 'TAX INVOICE',
        left: 820,
        top: 65,
        width: 340,
        fontSize: 28,
        fill: '#F5A524',
        fontWeight: 700,
        textAlign: 'right',
      }),
      text({
        text: 'Bill to\n{{customer_name}}\n{{customer_address}}',
        left: 80,
        top: 260,
        width: 520,
        fontSize: 28,
        fill: '#334155',
        lineHeight: 1.5,
      }),
      text({
        text: 'Invoice # {{invoice_no}}\nDate: {{invoice_date}}\nGSTIN: {{gstin}}',
        left: 700,
        top: 260,
        width: 460,
        fontSize: 28,
        fill: '#334155',
        textAlign: 'right',
        lineHeight: 1.5,
      }),
      rect({ left: 80, top: 500, width: 1080, height: 4, fill: '#E2E8F0' }),
      text({
        text: 'Description                          Amount\n{{line_1}}                          {{amount_1}}\n{{line_2}}                          {{amount_2}}',
        left: 80,
        top: 540,
        width: 1080,
        fontSize: 30,
        fill: '#0F172A',
        lineHeight: 1.9,
      }),
      text({
        text: 'Total (incl. GST):  {{total}}',
        left: 80,
        top: 1500,
        width: 1080,
        fontSize: 40,
        fill: '#0F172A',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        textAlign: 'right',
      }),
    ]),
  },
  {
    slug: 'whatsapp-catalog',
    name: 'WhatsApp Catalog Card',
    category: 'social',
    width: 1080,
    height: 1080,
    sortOrder: 180,
    canvas: doc('#ECFDF5', [
      rect({ left: 70, top: 70, width: 940, height: 940, fill: '#FFFFFF', rx: 32 }),
      text({
        text: 'CATALOGUE',
        left: 120,
        top: 140,
        width: 840,
        fontSize: 28,
        fill: '#059669',
        fontWeight: 700,
        charSpacing: 100,
      }),
      text({
        text: '{{product_name}}',
        left: 120,
        top: 220,
        width: 840,
        fontSize: 64,
        fill: '#064E3B',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      text({
        text: '{{description}}',
        left: 120,
        top: 360,
        width: 840,
        fontSize: 32,
        fill: '#047857',
      }),
      text({
        text: '₹ {{price}}',
        left: 120,
        top: 720,
        width: 840,
        fontSize: 72,
        fill: '#059669',
        fontFamily: FONT_DISPLAY,
        fontWeight: 900,
      }),
      text({
        text: 'Reply YES to order on WhatsApp',
        left: 120,
        top: 860,
        width: 840,
        fontSize: 28,
        fill: '#6B7280',
      }),
    ]),
  },
  {
    slug: 'brand-kit-starter',
    name: 'Brand Kit Starter — Square',
    category: 'brand',
    width: 1080,
    height: 1080,
    sortOrder: 190,
    canvas: doc('#FFFFFF', [
      rect({ left: 0, top: 0, width: 1080, height: 360, fill: '#3B8FD6' }),
      text({
        text: '{{brand_name}}',
        left: 80,
        top: 140,
        width: 920,
        fontSize: 72,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 900,
      }),
      text({
        text: 'Primary  ·  Secondary  ·  Accent',
        left: 80,
        top: 440,
        width: 920,
        fontSize: 28,
        fill: '#64748B',
      }),
      rect({ left: 80, top: 520, width: 200, height: 120, fill: '#3B8FD6', rx: 12 }),
      rect({ left: 320, top: 520, width: 200, height: 120, fill: '#F5A524', rx: 12 }),
      rect({ left: 560, top: 520, width: 200, height: 120, fill: '#E8618C', rx: 12 }),
      text({
        text: 'Logo slot — apply Brand Kit to replace colors & fonts',
        left: 80,
        top: 740,
        width: 920,
        fontSize: 32,
        fill: '#0F172A',
      }),
      text({
        text: '{{tagline}}',
        left: 80,
        top: 860,
        width: 920,
        fontSize: 28,
        fill: '#94A3B8',
      }),
    ]),
  },
]
