/**
 * Presentation deck templates — original Fabric layouts covering the free
 * Canva-template categories popular on SlidesCarnival (pitch, SWOT, roadmap,
 * education, portfolio, marketing plan, company profile, timeline).
 *
 * We do NOT scrape or convert Canva .canva files from SlidesCarnival; those
 * remain Canva/PPTX downloads. Users who need the Canva-format packs can open
 * https://www.slidescarnival.com/category/free-templates/canva-templates
 */
import type { SeedTemplate } from './templates.js'

type FabricObject = Record<string, unknown>

const FONT_DISPLAY = 'Montserrat'
const FONT_BODY = 'Inter'
const FONT_SERIF = 'Playfair Display'

function rect(o: {
  left: number
  top: number
  width: number
  height: number
  fill: string
  rx?: number
  opacity?: number
}): FabricObject {
  return {
    type: 'Rect',
    version: '6.0.0',
    originX: 'left',
    originY: 'top',
    rx: o.rx ?? 0,
    ry: o.rx ?? 0,
    opacity: o.opacity ?? 1,
    strokeWidth: 0,
    ...o,
  }
}

function circle(o: {
  left: number
  top: number
  radius: number
  fill: string
  opacity?: number
}): FabricObject {
  return {
    type: 'Circle',
    version: '6.0.0',
    originX: 'left',
    originY: 'top',
    opacity: o.opacity ?? 1,
    strokeWidth: 0,
    ...o,
  }
}

function text(o: {
  text: string
  left: number
  top: number
  width: number
  fontSize: number
  fill: string
  fontFamily?: string
  fontWeight?: string | number
  textAlign?: string
  lineHeight?: number
  charSpacing?: number
}): FabricObject {
  return {
    type: 'Textbox',
    version: '6.0.0',
    originX: 'left',
    originY: 'top',
    fontFamily: o.fontFamily ?? FONT_BODY,
    fontWeight: o.fontWeight ?? 'normal',
    textAlign: o.textAlign ?? 'left',
    lineHeight: o.lineHeight ?? 1.16,
    charSpacing: o.charSpacing ?? 0,
    splitByGrapheme: false,
    strokeWidth: 0,
    ...o,
  }
}

function doc(background: string, objects: FabricObject[]) {
  return { version: '6.0.0', background, objects }
}

const W = 1920
const H = 1080

export const DECK_TEMPLATES: SeedTemplate[] = [
  {
    slug: 'deck-pitch-cover',
    name: 'Pitch Deck — Cover',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 160,
    canvas: doc('#111827', [
      circle({ left: 1380, top: -180, radius: 520, fill: '#F59E0B', opacity: 0.2 }),
      circle({ left: -200, top: 720, radius: 380, fill: '#6366F1', opacity: 0.25 }),
      text({
        text: 'PITCH DECK',
        left: 140,
        top: 280,
        width: 900,
        fontSize: 28,
        fill: '#FBBF24',
        fontWeight: 700,
        charSpacing: 160,
      }),
      text({
        text: '{{company_name}}',
        left: 140,
        top: 360,
        width: 1400,
        fontSize: 96,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        lineHeight: 1.05,
      }),
      text({
        text: '{{tagline}}',
        left: 140,
        top: 520,
        width: 1200,
        fontSize: 40,
        fill: '#CBD5E1',
      }),
      text({
        text: '{{presenter}}  ·  {{date}}',
        left: 140,
        top: 920,
        width: 1000,
        fontSize: 28,
        fill: '#94A3B8',
      }),
    ]),
  },
  {
    slug: 'deck-problem-solution',
    name: 'Pitch — Problem & Solution',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 161,
    canvas: doc('#FFFFFF', [
      rect({ left: 0, top: 0, width: 960, height: 1080, fill: '#FEF2F2' }),
      rect({ left: 960, top: 0, width: 960, height: 1080, fill: '#ECFDF5' }),
      text({
        text: 'THE PROBLEM',
        left: 100,
        top: 120,
        width: 700,
        fontSize: 28,
        fill: '#DC2626',
        fontWeight: 700,
        charSpacing: 80,
      }),
      text({
        text: '{{problem}}',
        left: 100,
        top: 220,
        width: 740,
        fontSize: 48,
        fill: '#7F1D1D',
        fontFamily: FONT_DISPLAY,
        fontWeight: 700,
        lineHeight: 1.25,
      }),
      text({
        text: 'OUR SOLUTION',
        left: 1060,
        top: 120,
        width: 700,
        fontSize: 28,
        fill: '#059669',
        fontWeight: 700,
        charSpacing: 80,
      }),
      text({
        text: '{{solution}}',
        left: 1060,
        top: 220,
        width: 740,
        fontSize: 48,
        fill: '#064E3B',
        fontFamily: FONT_DISPLAY,
        fontWeight: 700,
        lineHeight: 1.25,
      }),
    ]),
  },
  {
    slug: 'deck-swot',
    name: 'Strategy — SWOT',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 162,
    canvas: doc('#0F172A', [
      text({
        text: 'SWOT Analysis',
        left: 80,
        top: 48,
        width: 800,
        fontSize: 48,
        fill: '#F8FAFC',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      rect({ left: 80, top: 140, width: 860, height: 420, fill: '#14532D', rx: 16 }),
      rect({ left: 980, top: 140, width: 860, height: 420, fill: '#1E3A8A', rx: 16 }),
      rect({ left: 80, top: 600, width: 860, height: 420, fill: '#9A3412', rx: 16 }),
      rect({ left: 980, top: 600, width: 860, height: 420, fill: '#581C87', rx: 16 }),
      text({
        text: 'Strengths\n{{strengths}}',
        left: 120,
        top: 180,
        width: 780,
        fontSize: 36,
        fill: '#ECFDF5',
        lineHeight: 1.4,
      }),
      text({
        text: 'Weaknesses\n{{weaknesses}}',
        left: 1020,
        top: 180,
        width: 780,
        fontSize: 36,
        fill: '#DBEAFE',
        lineHeight: 1.4,
      }),
      text({
        text: 'Opportunities\n{{opportunities}}',
        left: 120,
        top: 640,
        width: 780,
        fontSize: 36,
        fill: '#FFEDD5',
        lineHeight: 1.4,
      }),
      text({
        text: 'Threats\n{{threats}}',
        left: 1020,
        top: 640,
        width: 780,
        fontSize: 36,
        fill: '#F3E8FF',
        lineHeight: 1.4,
      }),
    ]),
  },
  {
    slug: 'deck-roadmap',
    name: 'Strategy — Roadmap',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 163,
    canvas: doc('#FFFBF5', [
      text({
        text: 'Product Roadmap',
        left: 100,
        top: 80,
        width: 1200,
        fontSize: 64,
        fill: '#1C1917',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      rect({ left: 100, top: 520, width: 1720, height: 12, fill: '#D6D3D1', rx: 6 }),
      circle({ left: 220, top: 492, radius: 28, fill: '#F59E0B' }),
      circle({ left: 640, top: 492, radius: 28, fill: '#3B82F6' }),
      circle({ left: 1060, top: 492, radius: 28, fill: '#10B981' }),
      circle({ left: 1480, top: 492, radius: 28, fill: '#8B5CF6' }),
      text({
        text: 'Q1\n{{q1}}',
        left: 140,
        top: 600,
        width: 320,
        fontSize: 32,
        fill: '#44403C',
        textAlign: 'center',
        lineHeight: 1.35,
      }),
      text({
        text: 'Q2\n{{q2}}',
        left: 560,
        top: 600,
        width: 320,
        fontSize: 32,
        fill: '#44403C',
        textAlign: 'center',
        lineHeight: 1.35,
      }),
      text({
        text: 'Q3\n{{q3}}',
        left: 980,
        top: 600,
        width: 320,
        fontSize: 32,
        fill: '#44403C',
        textAlign: 'center',
        lineHeight: 1.35,
      }),
      text({
        text: 'Q4\n{{q4}}',
        left: 1400,
        top: 600,
        width: 320,
        fontSize: 32,
        fill: '#44403C',
        textAlign: 'center',
        lineHeight: 1.35,
      }),
    ]),
  },
  {
    slug: 'deck-metrics',
    name: 'Business — Key Metrics',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 164,
    canvas: doc('#0B1220', [
      text({
        text: 'Traction at a glance',
        left: 100,
        top: 80,
        width: 1400,
        fontSize: 56,
        fill: '#F8FAFC',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      rect({ left: 100, top: 240, width: 520, height: 620, fill: '#1E293B', rx: 24 }),
      rect({ left: 700, top: 240, width: 520, height: 620, fill: '#1E293B', rx: 24 }),
      rect({ left: 1300, top: 240, width: 520, height: 620, fill: '#1E293B', rx: 24 }),
      text({
        text: '{{metric_1_value}}\n{{metric_1_label}}',
        left: 140,
        top: 420,
        width: 440,
        fontSize: 56,
        fill: '#38BDF8',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        textAlign: 'center',
        lineHeight: 1.4,
      }),
      text({
        text: '{{metric_2_value}}\n{{metric_2_label}}',
        left: 740,
        top: 420,
        width: 440,
        fontSize: 56,
        fill: '#34D399',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        textAlign: 'center',
        lineHeight: 1.4,
      }),
      text({
        text: '{{metric_3_value}}\n{{metric_3_label}}',
        left: 1340,
        top: 420,
        width: 440,
        fontSize: 56,
        fill: '#FBBF24',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        textAlign: 'center',
        lineHeight: 1.4,
      }),
    ]),
  },
  {
    slug: 'deck-team',
    name: 'Company — Team',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 165,
    canvas: doc('#F8FAFC', [
      text({
        text: 'Meet the team',
        left: 100,
        top: 80,
        width: 1200,
        fontSize: 64,
        fill: '#0F172A',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      rect({ left: 100, top: 220, width: 520, height: 700, fill: '#E2E8F0', rx: 20 }),
      rect({ left: 700, top: 220, width: 520, height: 700, fill: '#E2E8F0', rx: 20 }),
      rect({ left: 1300, top: 220, width: 520, height: 700, fill: '#E2E8F0', rx: 20 }),
      text({
        text: '{{name_1}}\n{{role_1}}',
        left: 140,
        top: 720,
        width: 440,
        fontSize: 32,
        fill: '#0F172A',
        textAlign: 'center',
        lineHeight: 1.4,
        fontWeight: 700,
      }),
      text({
        text: '{{name_2}}\n{{role_2}}',
        left: 740,
        top: 720,
        width: 440,
        fontSize: 32,
        fill: '#0F172A',
        textAlign: 'center',
        lineHeight: 1.4,
        fontWeight: 700,
      }),
      text({
        text: '{{name_3}}\n{{role_3}}',
        left: 1340,
        top: 720,
        width: 440,
        fontSize: 32,
        fill: '#0F172A',
        textAlign: 'center',
        lineHeight: 1.4,
        fontWeight: 700,
      }),
    ]),
  },
  {
    slug: 'deck-timeline',
    name: 'Company — Timeline',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 166,
    canvas: doc('#1E1B4B', [
      text({
        text: 'Our journey',
        left: 100,
        top: 80,
        width: 1000,
        fontSize: 64,
        fill: '#EEF2FF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      rect({ left: 160, top: 360, width: 1600, height: 8, fill: '#A5B4FC', rx: 4 }),
      text({
        text: '{{year_1}}\n{{milestone_1}}',
        left: 120,
        top: 440,
        width: 360,
        fontSize: 30,
        fill: '#C7D2FE',
        lineHeight: 1.4,
      }),
      text({
        text: '{{year_2}}\n{{milestone_2}}',
        left: 560,
        top: 440,
        width: 360,
        fontSize: 30,
        fill: '#C7D2FE',
        lineHeight: 1.4,
      }),
      text({
        text: '{{year_3}}\n{{milestone_3}}',
        left: 1000,
        top: 440,
        width: 360,
        fontSize: 30,
        fill: '#C7D2FE',
        lineHeight: 1.4,
      }),
      text({
        text: '{{year_4}}\n{{milestone_4}}',
        left: 1440,
        top: 440,
        width: 360,
        fontSize: 30,
        fill: '#C7D2FE',
        lineHeight: 1.4,
      }),
    ]),
  },
  {
    slug: 'deck-education-lesson',
    name: 'Education — Lesson Title',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 167,
    canvas: doc('#ECFEFF', [
      rect({ left: 0, top: 0, width: 1920, height: 160, fill: '#0891B2' }),
      text({
        text: 'LESSON {{lesson_number}}',
        left: 100,
        top: 55,
        width: 800,
        fontSize: 28,
        fill: '#CFFAFE',
        fontWeight: 700,
        charSpacing: 100,
      }),
      text({
        text: '{{lesson_title}}',
        left: 100,
        top: 320,
        width: 1600,
        fontSize: 80,
        fill: '#164E63',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        lineHeight: 1.1,
      }),
      text({
        text: '{{learning_goal}}',
        left: 100,
        top: 520,
        width: 1500,
        fontSize: 36,
        fill: '#0E7490',
        lineHeight: 1.4,
      }),
      text({
        text: '{{grade_level}}  ·  {{duration}}',
        left: 100,
        top: 920,
        width: 1000,
        fontSize: 28,
        fill: '#155E75',
      }),
    ]),
  },
  {
    slug: 'deck-marketing-plan',
    name: 'Marketing — Plan Overview',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 168,
    canvas: doc('#FFF7ED', [
      text({
        text: 'Marketing plan',
        left: 100,
        top: 80,
        width: 1200,
        fontSize: 64,
        fill: '#9A3412',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      rect({ left: 100, top: 220, width: 400, height: 720, fill: '#FED7AA', rx: 20 }),
      rect({ left: 560, top: 220, width: 400, height: 720, fill: '#FDBA74', rx: 20 }),
      rect({ left: 1020, top: 220, width: 400, height: 720, fill: '#FB923C', rx: 20 }),
      rect({ left: 1480, top: 220, width: 340, height: 720, fill: '#EA580C', rx: 20 }),
      text({
        text: '01 Audience\n{{audience}}',
        left: 130,
        top: 280,
        width: 340,
        fontSize: 32,
        fill: '#7C2D12',
        lineHeight: 1.45,
        fontWeight: 700,
      }),
      text({
        text: '02 Channels\n{{channels}}',
        left: 590,
        top: 280,
        width: 340,
        fontSize: 32,
        fill: '#7C2D12',
        lineHeight: 1.45,
        fontWeight: 700,
      }),
      text({
        text: '03 Message\n{{message}}',
        left: 1050,
        top: 280,
        width: 340,
        fontSize: 32,
        fill: '#7C2D12',
        lineHeight: 1.45,
        fontWeight: 700,
      }),
      text({
        text: '04 KPI\n{{kpi}}',
        left: 1510,
        top: 280,
        width: 280,
        fontSize: 32,
        fill: '#FFF7ED',
        lineHeight: 1.45,
        fontWeight: 700,
      }),
    ]),
  },
  {
    slug: 'deck-portfolio-cover',
    name: 'Portfolio — Cover',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 169,
    canvas: doc('#FAF5FF', [
      rect({ left: 0, top: 0, width: 720, height: 1080, fill: '#7C3AED' }),
      text({
        text: 'PORTFOLIO',
        left: 80,
        top: 400,
        width: 560,
        fontSize: 28,
        fill: '#E9D5FF',
        fontWeight: 700,
        charSpacing: 140,
      }),
      text({
        text: '{{name}}',
        left: 80,
        top: 480,
        width: 560,
        fontSize: 72,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        lineHeight: 1.1,
      }),
      text({
        text: '{{role}}',
        left: 80,
        top: 620,
        width: 560,
        fontSize: 32,
        fill: '#DDD6FE',
      }),
      text({
        text: '{{bio}}',
        left: 860,
        top: 360,
        width: 900,
        fontSize: 40,
        fill: '#4C1D95',
        fontFamily: FONT_SERIF,
        lineHeight: 1.45,
      }),
      text({
        text: '{{contact}}',
        left: 860,
        top: 900,
        width: 900,
        fontSize: 28,
        fill: '#6D28D9',
      }),
    ]),
  },
  {
    slug: 'deck-company-profile',
    name: 'Business — Company Profile',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 170,
    canvas: doc('#FFFFFF', [
      rect({ left: 0, top: 0, width: 1920, height: 280, fill: '#0F172A' }),
      text({
        text: '{{company_name}}',
        left: 100,
        top: 90,
        width: 1400,
        fontSize: 64,
        fill: '#F8FAFC',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
      }),
      text({
        text: '{{industry}}  ·  {{founded}}',
        left: 100,
        top: 180,
        width: 1000,
        fontSize: 28,
        fill: '#94A3B8',
      }),
      text({
        text: 'About us',
        left: 100,
        top: 360,
        width: 600,
        fontSize: 36,
        fill: '#0F172A',
        fontWeight: 700,
      }),
      text({
        text: '{{about}}',
        left: 100,
        top: 430,
        width: 1000,
        fontSize: 32,
        fill: '#334155',
        lineHeight: 1.5,
      }),
      text({
        text: 'Mission\n{{mission}}',
        left: 1200,
        top: 360,
        width: 600,
        fontSize: 32,
        fill: '#1E293B',
        lineHeight: 1.45,
      }),
      text({
        text: 'Vision\n{{vision}}',
        left: 1200,
        top: 620,
        width: 600,
        fontSize: 32,
        fill: '#1E293B',
        lineHeight: 1.45,
      }),
    ]),
  },
  {
    slug: 'deck-closing',
    name: 'Pitch — Thank You / CTA',
    category: 'presentation',
    width: W,
    height: H,
    sortOrder: 171,
    canvas: doc('#0B1220', [
      circle({ left: -120, top: -120, radius: 360, fill: '#3B82F6', opacity: 0.2 }),
      text({
        text: 'Thank you',
        left: 160,
        top: 320,
        width: 1600,
        fontSize: 110,
        fill: '#FFFFFF',
        fontFamily: FONT_DISPLAY,
        fontWeight: 800,
        textAlign: 'center',
      }),
      text({
        text: '{{cta}}',
        left: 260,
        top: 500,
        width: 1400,
        fontSize: 40,
        fill: '#94A3B8',
        textAlign: 'center',
      }),
      rect({ left: 710, top: 680, width: 500, height: 88, fill: '#3B82F6', rx: 44 }),
      text({
        text: '{{button_label}}',
        left: 710,
        top: 702,
        width: 500,
        fontSize: 32,
        fill: '#FFFFFF',
        fontWeight: 700,
        textAlign: 'center',
      }),
      text({
        text: '{{contact}}',
        left: 260,
        top: 860,
        width: 1400,
        fontSize: 28,
        fill: '#64748B',
        textAlign: 'center',
      }),
    ]),
  },
]
