# Disable the default option to open a blank issue
blank_issues_enabled: true

# Define your custom links
contact_links:
  - name: Documentation / product
    url: https://indobase.in
    about: Indobase product and docs

  - name: Security Issue
    url: https://github.com/Indobase/Indobase/security/advisories/new
    about: Please submit security issues via GitHub Security Advisories.
