#!/usr/bin/env node
/**
 * Indobase app-host provisioner
 *
 * Deploys Builder static apps as nginx containers and writes Traefik file routes
 * (Vyom .248 uses providers.file, not Docker labels).
 */
import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { createHash, timingSafeEqual } from 'node:crypto';

const PORT = Number(process.env.APP_HOST_PORT || 8791);
const TOKEN = process.env.APP_HOST_TOKEN || '';
const ROOT = process.env.APP_HOST_ROOT || '/var/lib/indobase/apps';
const DOMAIN = process.env.APP_HOST_DOMAIN || 'indobase.in';
const NETWORK = process.env.APP_HOST_NETWORK || 'docker_default';
const IMAGE = process.env.APP_HOST_NGINX_IMAGE || 'nginx:1.27-alpine';
const TRAEFIK_DYNAMIC = process.env.APP_HOST_TRAEFIK_DYNAMIC || '/var/lib/indobase/traefik-dynamic';

function json(res, status, body) {
  const payload = JSON.stringify(body);
  res.writeHead(status, {
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(payload),
  });
  res.end(payload);
}

function safeSlug(input) {
  const slug = String(input || '')
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 48);
  return slug || null;
}

function authorize(req) {
  if (!TOKEN) {
    return true;
  }

  const header = req.headers.authorization || '';
  const bearer = header.startsWith('Bearer ') ? header.slice(7) : '';
  const alt = req.headers['x-app-host-token'] || '';
  const provided = bearer || alt;

  if (!provided || provided.length !== TOKEN.length) {
    return false;
  }

  try {
    return timingSafeEqual(Buffer.from(provided), Buffer.from(TOKEN));
  } catch {
    return false;
  }
}

function run(command, args, options = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      stdio: ['ignore', 'pipe', 'pipe'],
      ...options,
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk) => {
      stdout += chunk;
    });
    child.stderr.on('data', (chunk) => {
      stderr += chunk;
    });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) {
        resolve({ stdout, stderr });
      } else {
        reject(new Error(stderr || stdout || `${command} exited ${code}`));
      }
    });
  });
}

async function ensureNetwork() {
  try {
    await run('docker', ['network', 'inspect', NETWORK]);
  } catch {
    await run('docker', ['network', 'create', NETWORK]);
  }
}

async function writeFiles(appDir, files) {
  await fs.mkdir(appDir, { recursive: true });
  const entries = Object.entries(files || {});

  for (const [rel, content] of entries) {
    const cleaned = String(rel).replace(/^\/+/, '').replace(/\.\./g, '');
    if (!cleaned || cleaned.endsWith('/')) {
      continue;
    }

    const target = path.join(appDir, cleaned);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, typeof content === 'string' ? content : String(content ?? ''), 'utf8');
  }
}

function containerName(slug) {
  return `indobase-app-${slug}`;
}

function traefikRouteYaml(slug, name) {
  const host = `${slug}.${DOMAIN}`;
  return `# Generated by indobase-app-host
http:
  routers:
    ${name}-http:
      rule: Host(\`${host}\`)
      priority: 200
      middlewares:
        - redirect-to-https
      service: ${name}
      entryPoints:
        - web
    ${name}-https:
      rule: Host(\`${host}\`)
      priority: 200
      service: ${name}
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
  services:
    ${name}:
      loadBalancer:
        servers:
          - url: http://${name}:80
`;
}

async function writeTraefikRoute(slug) {
  const name = containerName(slug);
  await fs.mkdir(TRAEFIK_DYNAMIC, { recursive: true });
  await fs.writeFile(path.join(TRAEFIK_DYNAMIC, `app-${slug}.yml`), traefikRouteYaml(slug, name), 'utf8');
}

async function removeTraefikRoute(slug) {
  await fs.rm(path.join(TRAEFIK_DYNAMIC, `app-${slug}.yml`), { force: true });
}

async function deployApp({ slug, files }) {
  const appDir = path.join(ROOT, slug, 'www');
  await writeFiles(appDir, files);
  await ensureNetwork();

  const name = containerName(slug);
  try {
    await run('docker', ['rm', '-f', name]);
  } catch {
    // ok if missing
  }

  await run('docker', [
    'run',
    '-d',
    '--name',
    name,
    '--restart',
    'unless-stopped',
    '--network',
    NETWORK,
    '-v',
    `${appDir}:/usr/share/nginx/html:ro`,
    IMAGE,
  ]);

  // Ensure Traefik can resolve the container (same docker network).
  try {
    await run('docker', ['network', 'connect', NETWORK, 'indobase-backend-traefik']);
  } catch {
    // already connected
  }

  await writeTraefikRoute(slug);

  const hash = createHash('sha256')
    .update(JSON.stringify(Object.keys(files || {}).sort()))
    .digest('hex')
    .slice(0, 12);

  return {
    slug,
    url: `https://${slug}.${DOMAIN}`,
    container: name,
    files: Object.keys(files || {}).length,
    revision: hash,
  };
}

async function listApps() {
  try {
    const { stdout } = await run('docker', [
      'ps',
      '--filter',
      'name=indobase-app-',
      '--format',
      '{{.Names}}\t{{.Status}}',
    ]);
    return stdout
      .trim()
      .split('\n')
      .filter(Boolean)
      .map((line) => {
        const [name, ...statusParts] = line.split('\t');
        const slug = name.replace(/^indobase-app-/, '');
        return { slug, container: name, status: statusParts.join('\t'), url: `https://${slug}.${DOMAIN}` };
      });
  } catch {
    return [];
  }
}

async function removeApp(slug) {
  const name = containerName(slug);
  try {
    await run('docker', ['rm', '-f', name]);
  } catch {
    // ignore
  }
  await removeTraefikRoute(slug);
  await fs.rm(path.join(ROOT, slug), { recursive: true, force: true });
  return { ok: true, slug };
}

async function readBody(req) {
  const chunks = [];
  for await (const chunk of req) {
    chunks.push(chunk);
  }
  const raw = Buffer.concat(chunks).toString('utf8');
  if (!raw) {
    return {};
  }
  return JSON.parse(raw);
}

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url || '/', `http://${req.headers.host || 'localhost'}`);

    if (req.method === 'GET' && url.pathname === '/health') {
      return json(res, 200, {
        ok: true,
        service: 'indobase-app-host',
        domain: DOMAIN,
        root: ROOT,
      });
    }

    if (!authorize(req)) {
      return json(res, 401, { ok: false, message: 'Unauthorized' });
    }

    if (req.method === 'GET' && url.pathname === '/apps') {
      return json(res, 200, { ok: true, apps: await listApps() });
    }

    if (req.method === 'POST' && url.pathname === '/deploy') {
      const body = await readBody(req);
      const slug = safeSlug(body.slug);
      if (!slug) {
        return json(res, 400, { ok: false, message: 'slug is required' });
      }
      if (!body.files || typeof body.files !== 'object') {
        return json(res, 400, { ok: false, message: 'files map is required' });
      }

      const result = await deployApp({ slug, files: body.files });
      return json(res, 200, { ok: true, ...result });
    }

    const deleteMatch = url.pathname.match(/^\/apps\/([a-z0-9-]+)$/);
    if (req.method === 'DELETE' && deleteMatch) {
      const result = await removeApp(deleteMatch[1]);
      return json(res, 200, result);
    }

    return json(res, 404, { ok: false, message: 'Not found' });
  } catch (error) {
    return json(res, 500, {
      ok: false,
      message: error instanceof Error ? error.message : 'App host error',
    });
  }
});

server.listen(PORT, '0.0.0.0', () => {
  console.log(`[app-host] listening on :${PORT} domain=${DOMAIN} root=${ROOT}`);
});
