sonar.projectKey=indobase_indobase-social
sonar.projectName=Indobase Social
sonar.projectDescription=Indobase Social media scheduling (fork of Postiz / AGPL)

# Scan Performace
sonar.javascript.node.maxspace=4096
sonar.typescript.tsconfigPath=tsconfig.base.json
