/**
 * Canonical per-tenant Traefik dynamic config (stripPrefix + correct host ports).
 * Used by the data-plane provisioner after compose up and by VPS repair scripts.
 */
import fs from 'node:fs'
import path from 'node:path'
import { execSync } from 'node:child_process'

export function getDockerPsLines() {
  return execSync('docker ps --format "{{.Names}}\t{{.Ports}}"', { encoding: 'utf8' })
}

export function hostPortFor(dockerPs, ref, svc) {
  const needles =
    svc === 'realtime'
      ? [`${ref}.indobase-realtime`, `${ref}-tenant-realtime`, `indobase-tenant-${ref}-tenant-realtime`]
      : [`${ref}-tenant-${svc}`, `indobase-tenant-${ref}-tenant-${svc}`]
  const line = dockerPs.split('\n').find((l) => needles.some((n) => l.includes(n)))
  if (!line) return null
  const m = line.match(/0\.0\.0\.0:(\d+)->/)
  return m ? Number(m[1]) : null
}

export function buildTenantTraefikYaml(ref, hostRule, upstream, ports) {
  const strip = (name, prefix) => `    tenant-${ref}-${name}-strip:
      stripPrefix:
        prefixes:
          - "${prefix}"
`
  return `# Generated by Studio — per-project routing (REST, Auth, Storage, Realtime, Functions)
http:
  middlewares:
${strip('rest', '/rest/v1')}${strip('auth', '/auth/v1')}${strip('storage', '/storage/v1')}${strip('realtime', '/realtime/v1')}${strip('functions', '/functions/v1')}
  routers:
    tenant-${ref}-rest:
      rule: Host(\`${hostRule}\`) && PathPrefix(\`/rest/v1\`)
      middlewares:
        - tenant-${ref}-rest-strip
      service: tenant-${ref}-rest
      entryPoints: [web, websecure]
    tenant-${ref}-auth:
      rule: Host(\`${hostRule}\`) && PathPrefix(\`/auth/v1\`)
      middlewares:
        - tenant-${ref}-auth-strip
      service: tenant-${ref}-auth
      entryPoints: [web, websecure]
    tenant-${ref}-storage:
      rule: Host(\`${hostRule}\`) && PathPrefix(\`/storage/v1\`)
      middlewares:
        - tenant-${ref}-storage-strip
      service: tenant-${ref}-storage
      entryPoints: [web, websecure]
    tenant-${ref}-realtime:
      rule: Host(\`${hostRule}\`) && PathPrefix(\`/realtime/v1\`)
      middlewares:
        - tenant-${ref}-realtime-strip
      service: tenant-${ref}-realtime
      entryPoints: [web, websecure]
    tenant-${ref}-functions:
      rule: Host(\`${hostRule}\`) && PathPrefix(\`/functions/v1\`)
      middlewares:
        - tenant-${ref}-functions-strip
      service: tenant-${ref}-functions
      entryPoints: [web, websecure]

  services:
    tenant-${ref}-rest:
      loadBalancer:
        servers: [{ url: "http://${upstream}:${ports.rest}" }]
        passHostHeader: true
    tenant-${ref}-auth:
      loadBalancer:
        servers: [{ url: "http://${upstream}:${ports.auth}" }]
        passHostHeader: true
    tenant-${ref}-storage:
      loadBalancer:
        servers: [{ url: "http://${upstream}:${ports.storage}" }]
        passHostHeader: true
    tenant-${ref}-realtime:
      loadBalancer:
        servers: [{ url: "http://${upstream}:${ports.realtime}" }]
        passHostHeader: true
    tenant-${ref}-functions:
      loadBalancer:
        servers: [{ url: "http://${upstream}:${ports.functions}" }]
        passHostHeader: true
`
}

/**
 * Rewrite tenant-<ref>.yml from live docker published ports. Returns false if stack not running.
 */
export function fixTenantTraefikForRef(ref, traefikDir, opts = {}) {
  const upstream = opts.upstream || process.env.TRAEFIK_UPSTREAM_HOST?.trim() || '172.17.0.1'
  const domain = opts.domain || process.env.PUBLIC_DOMAIN?.trim() || 'indobase.in'
  const dockerPs = opts.dockerPs || getDockerPsLines()
  const ports = {
    rest: hostPortFor(dockerPs, ref, 'rest'),
    auth: hostPortFor(dockerPs, ref, 'auth'),
    storage: hostPortFor(dockerPs, ref, 'storage'),
    realtime: hostPortFor(dockerPs, ref, 'realtime'),
    functions: hostPortFor(dockerPs, ref, 'functions'),
  }
  if (Object.values(ports).some((p) => !p)) {
    return { ok: false, ref, ports, reason: 'stack_not_running' }
  }
  const traefikPath = path.join(traefikDir, `tenant-${ref}.yml`)
  fs.writeFileSync(
    traefikPath,
    buildTenantTraefikYaml(ref, `${ref}.${domain}`, upstream, ports),
    'utf8'
  )
  return { ok: true, ref, ports, traefikPath }
}

export function fixAllTenantTraefikFromDocker(traefikDir, opts = {}) {
  const dockerPs = getDockerPsLines()
  const refs = new Set()
  for (const line of dockerPs.split('\n')) {
    const m = line.match(/indobase-tenant-([a-z0-9-]+)-tenant-rest/)
    if (m) refs.add(m[1])
  }
  const results = []
  for (const ref of refs) {
    results.push(fixTenantTraefikForRef(ref, traefikDir, { ...opts, dockerPs }))
  }
  return results
}
