/**
 * Canonical per-tenant Traefik dynamic config (stripPrefix + correct host ports).
 * Used by the data-plane provisioner after compose up and by VPS repair scripts.
 */
import fs from 'node:fs'
import path from 'node:path'
import { execSync } from 'node:child_process'
import { readSiteRoutes } from './site-routes.mjs'

export function getDockerPsLines() {
  return execSync('docker ps --format "{{.Names}}\t{{.Ports}}"', { encoding: 'utf8' })
}

export function hostPortFor(dockerPs, ref, svc) {
  const needles =
    svc === 'realtime'
      ? [`${ref}.indobase-realtime`, `${ref}-tenant-realtime`, `indobase-tenant-${ref}-tenant-realtime`]
      : svc === 'site'
        ? [`${ref}-tenant-site`, `indobase-tenant-${ref}-tenant-site`]
        : [`${ref}-tenant-${svc}`, `indobase-tenant-${ref}-tenant-${svc}`]
  const line = dockerPs.split('\n').find((l) => needles.some((n) => l.includes(n)))
  if (!line) return null
  const m = line.match(/(?:0\.0\.0\.0|127\.0\.0\.1|172\.17\.0\.1):(\d+)->/)
  return m ? Number(m[1]) : null
}

export function buildTenantTraefikYaml(ref, hostRule, upstream, ports, opts = {}) {
  const siteProxyPort =
    opts.siteProxyPort != null && Number.isFinite(Number(opts.siteProxyPort))
      ? Number(opts.siteProxyPort)
      : null
  const sitePort = siteProxyPort != null ? siteProxyPort : ports.site

  const strip = (name, prefix) => `    tenant-${ref}-${name}-strip:
      stripPrefix:
        prefixes:
          - "${prefix}"
`
  /*
   * Browser CORS for the data APIs. Generated apps (and the Builder preview)
   * call these endpoints cross-origin via supabase-js, which sends an `apikey`
   * (and `x-client-info`) header — so every request is preflighted. GoTrue is
   * exposed directly (no Kong gateway) and its built-in CORS allow-list does
   * NOT include `apikey`, so it rejects the preflight with 204 and no
   * Access-Control-* headers -> the browser reports "Failed to fetch". Handle
   * the preflight at Traefik for all API routers. Traefik answers OPTIONS
   * itself and Set()s (overwrites, not appends) Access-Control-Allow-Origin on
   * real responses, so there is no duplicate header with GoTrue/PostgREST.
   */
  const corsMiddleware = `    tenant-${ref}-cors:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD]
        accessControlAllowHeaders: [authorization, apikey, content-type, x-client-info, x-supabase-api-version, accept, accept-profile, content-profile, prefer, x-upsert, range, x-region, x-requested-with]
        accessControlMaxAge: 86400
        addVaryHeader: true
`
  const apiRouter = (name, prefix) => `    tenant-${ref}-${name}:
      rule: Host(\`${hostRule}\`) && PathPrefix(\`${prefix}\`)
      priority: 300
      middlewares:
        - redirect-to-https
      service: tenant-${ref}-${name}
      entryPoints:
        - web
    tenant-${ref}-${name}-https:
      rule: Host(\`${hostRule}\`) && PathPrefix(\`${prefix}\`)
      priority: 300
      middlewares:
        - tenant-${ref}-cors
        - tenant-${ref}-${name}-strip
      service: tenant-${ref}-${name}
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
`

  const siteRouter =
    sitePort != null
      ? `    tenant-${ref}-site:
      rule: Host(\`${hostRule}\`)
      priority: 250
      middlewares:
        - redirect-to-https
      service: tenant-${ref}-site
      entryPoints:
        - web
    tenant-${ref}-site-https:
      rule: Host(\`${hostRule}\`)
      priority: 250
      service: tenant-${ref}-site
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
`
      : ''

  const siteService =
    sitePort != null
      ? `    tenant-${ref}-site:
      loadBalancer:
        servers: [{ url: "http://${upstream}:${sitePort}" }]
        passHostHeader: true
`
      : ''

  return `# Generated by Studio — per-project routing (REST, Auth, Storage, Realtime, Functions, Site)
http:
  middlewares:
${corsMiddleware}${strip('rest', '/rest/v1')}${strip('auth', '/auth/v1')}${strip('storage', '/storage/v1')}${strip('s3', '/s3')}${strip('realtime', '/realtime/v1')}${strip('functions', '/functions/v1')}
  routers:
${apiRouter('rest', '/rest/v1')}${apiRouter('auth', '/auth/v1')}${apiRouter('storage', '/storage/v1')}${apiRouter('s3', '/s3')}${apiRouter('realtime', '/realtime/v1')}${apiRouter('functions', '/functions/v1')}${siteRouter}
  services:
    tenant-${ref}-rest:
      loadBalancer:
        servers: [{ url: "http://${upstream}:${ports.rest}" }]
        passHostHeader: true
    tenant-${ref}-auth:
      loadBalancer:
        servers: [{ url: "http://${upstream}:${ports.auth}" }]
        passHostHeader: true
    tenant-${ref}-storage:
      loadBalancer:
        servers: [{ url: "http://${upstream}:${ports.storage}" }]
        passHostHeader: true
    tenant-${ref}-realtime:
      loadBalancer:
        servers: [{ url: "http://${upstream}:${ports.realtime}" }]
        passHostHeader: true
    tenant-${ref}-functions:
      loadBalancer:
        servers: [{ url: "http://${upstream}:${ports.functions}" }]
        passHostHeader: true
${siteService}`
}

/**
 * Rewrite tenant-<ref>.yml from live docker published ports. Returns false if stack not running.
 */
export function fixTenantTraefikForRef(ref, traefikDir, opts = {}) {
  const upstream = opts.upstream || process.env.TRAEFIK_UPSTREAM_HOST?.trim() || '172.17.0.1'
  const domain = opts.domain || process.env.PUBLIC_DOMAIN?.trim() || 'indobase.in'
  const dockerPs = opts.dockerPs || getDockerPsLines()
  const ports = {
    rest: hostPortFor(dockerPs, ref, 'rest'),
    auth: hostPortFor(dockerPs, ref, 'auth'),
    storage: hostPortFor(dockerPs, ref, 'storage'),
    realtime: hostPortFor(dockerPs, ref, 'realtime'),
    functions: hostPortFor(dockerPs, ref, 'functions'),
    site: hostPortFor(dockerPs, ref, 'site'),
  }
  const requiredPorts = ['rest', 'auth', 'storage', 'realtime', 'functions']
  if (requiredPorts.some((key) => ports[key] == null)) {
    return { ok: false, ref, ports, reason: 'stack_not_running' }
  }

  const siteRoutes = readSiteRoutes(traefikDir)
  const hasSiteRoute = Boolean(siteRoutes[ref])
  let siteProxyPort =
    opts.siteProxyPort != null && Number.isFinite(Number(opts.siteProxyPort))
      ? Number(opts.siteProxyPort)
      : null
  if (hasSiteRoute && siteProxyPort == null) {
    siteProxyPort = Number(process.env.SITE_STATIC_PROXY_PORT || 8790)
  }

  const traefikPath = path.join(traefikDir, `tenant-${ref}.yml`)
  fs.writeFileSync(
    traefikPath,
    buildTenantTraefikYaml(ref, `${ref}.${domain}`, upstream, ports, {
      siteProxyPort,
    }),
    'utf8'
  )
  return { ok: true, ref, ports, traefikPath, site_proxy_port: siteProxyPort }
}

export function fixAllTenantTraefikFromDocker(traefikDir, opts = {}) {
  const dockerPs = getDockerPsLines()
  const refs = new Set()
  for (const line of dockerPs.split('\n')) {
    const m = line.match(/indobase-tenant-([a-z0-9-]+)-tenant-rest/)
    if (m) refs.add(m[1])
  }
  const results = []
  for (const ref of refs) {
    results.push(fixTenantTraefikForRef(ref, traefikDir, { ...opts, dockerPs }))
  }
  return results
}
