-- Indobase plugin marketplace registry.
-- Adds publisher-managed plugin listings, versions, installs, reviews, and categories.

create table if not exists saas.plugin_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text null,
  inserted_at timestamptz not null default now()
);

insert into saas.plugin_categories (slug, name, description)
values
  ('developer-tools', 'Developer Tools', 'Plugins that improve developer workflows and tooling.'),
  ('database', 'Database', 'Plugins focused on database querying, schema, and data workflows.'),
  ('auth', 'Auth', 'Plugins for auth, identity, OAuth, and access management.'),
  ('mcp', 'MCP', 'Plugins and integrations powered by the Model Context Protocol.'),
  ('integrations', 'Integrations', 'Plugins that connect Indobase to external platforms and services.'),
  ('ai', 'AI', 'Plugins for prompts, agents, models, and AI-assisted development.')
on conflict (slug) do nothing;

create table if not exists saas.plugin_listings (
  id uuid primary key default gen_random_uuid(),
  organization_id integer not null references saas.organizations(id) on delete cascade,
  oauth_app_id text null,
  oauth_app_client_id text null,
  oauth_authorize_url text null,
  oauth_redirect_uri text null,
  slug text not null unique,
  name text not null,
  summary text not null default '',
  description_md text not null default '',
  website text null,
  repo_url text null,
  package_type text not null check (package_type in ('cursor_plugin', 'mcp_server')),
  source_type text not null check (source_type in ('github_repo', 'manifest_url', 'mcp_endpoint')),
  visibility text not null default 'draft' check (visibility in ('draft', 'public', 'unlisted', 'archived')),
  review_status text not null default 'draft'
    check (review_status in ('draft', 'submitted', 'approved', 'rejected', 'changes_requested')),
  pricing_model text not null default 'free' check (pricing_model in ('free', 'paid', 'contact')),
  logo_url text null,
  tags text[] not null default '{}'::text[],
  supported_clients text[] not null default '{}'::text[],
  supported_runtimes text[] not null default '{}'::text[],
  install_type text not null default 'mcp' check (install_type in ('mcp', 'plugin_repo', 'hybrid')),
  default_mcp_url text null,
  default_mcp_server_name text not null default 'plugin',
  source_metadata jsonb not null default '{}'::jsonb,
  latest_version_id uuid null,
  published_version_id uuid null,
  latest_validation_status text not null default 'pending'
    check (latest_validation_status in ('pending', 'valid', 'invalid')),
  published_at timestamptz null,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists saas.plugin_versions (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references saas.plugin_listings(id) on delete cascade,
  version text not null,
  changelog text null,
  source_ref text null,
  manifest_path text not null default '.cursor-plugin/plugin.json',
  readme_path text not null default 'README.md',
  mcp_path text null default '.mcp.json',
  package_metadata jsonb not null default '{}'::jsonb,
  manifest_json jsonb null,
  package_files jsonb not null default '[]'::jsonb,
  validation_status text not null default 'pending'
    check (validation_status in ('pending', 'valid', 'invalid')),
  validation_errors jsonb not null default '[]'::jsonb,
  validation_warnings jsonb not null default '[]'::jsonb,
  review_status text not null default 'draft'
    check (review_status in ('draft', 'submitted', 'approved', 'rejected', 'changes_requested')),
  reviewed_by_gotrue_id uuid null,
  reviewed_at timestamptz null,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (listing_id, version)
);

create table if not exists saas.plugin_assets (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references saas.plugin_listings(id) on delete cascade,
  version_id uuid null references saas.plugin_versions(id) on delete set null,
  asset_type text not null check (asset_type in ('logo', 'screenshot', 'archive', 'manifest', 'readme')),
  url text not null,
  metadata jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now()
);

create table if not exists saas.plugin_installs (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references saas.plugin_listings(id) on delete cascade,
  version_id uuid null references saas.plugin_versions(id) on delete set null,
  organization_id integer null references saas.organizations(id) on delete set null,
  project_ref text null references saas.projects(ref) on delete set null,
  installed_by_gotrue_id uuid null,
  client text not null,
  install_status text not null default 'requested'
    check (install_status in ('requested', 'authorized', 'installed', 'failed', 'revoked')),
  install_payload jsonb not null default '{}'::jsonb,
  authorization_url text null,
  authorization_completed_at timestamptz null,
  installed_at timestamptz null,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists saas.plugin_reviews (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references saas.plugin_listings(id) on delete cascade,
  version_id uuid null references saas.plugin_versions(id) on delete set null,
  reviewer_gotrue_id uuid null,
  status text not null check (status in ('submitted', 'approved', 'rejected', 'changes_requested')),
  notes text null,
  metadata jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now()
);

create table if not exists saas.plugin_listing_categories (
  listing_id uuid not null references saas.plugin_listings(id) on delete cascade,
  category_id bigint not null references saas.plugin_categories(id) on delete cascade,
  primary key (listing_id, category_id)
);

do $$
begin
  begin
    alter table saas.plugin_listings
      add constraint plugin_listings_latest_version_fk
      foreign key (latest_version_id) references saas.plugin_versions(id) on delete set null;
  exception when duplicate_object then null;
  end;

  begin
    alter table saas.plugin_listings
      add constraint plugin_listings_published_version_fk
      foreign key (published_version_id) references saas.plugin_versions(id) on delete set null;
  exception when duplicate_object then null;
  end;
end $$;

create index if not exists plugin_listings_org_idx
  on saas.plugin_listings (organization_id, inserted_at desc);

create index if not exists plugin_listings_visibility_review_idx
  on saas.plugin_listings (visibility, review_status, published_at desc nulls last);

create index if not exists plugin_listings_name_trgm_idx
  on saas.plugin_listings using gin (name gin_trgm_ops);

create index if not exists plugin_listings_slug_trgm_idx
  on saas.plugin_listings using gin (slug gin_trgm_ops);

create index if not exists plugin_listings_tags_gin_idx
  on saas.plugin_listings using gin (tags);

create index if not exists plugin_versions_listing_idx
  on saas.plugin_versions (listing_id, inserted_at desc);

create index if not exists plugin_installs_listing_client_idx
  on saas.plugin_installs (listing_id, client, inserted_at desc);

create index if not exists plugin_reviews_listing_idx
  on saas.plugin_reviews (listing_id, inserted_at desc);

alter table saas.plugin_categories enable row level security;
alter table saas.plugin_listings enable row level security;
alter table saas.plugin_versions enable row level security;
alter table saas.plugin_assets enable row level security;
alter table saas.plugin_installs enable row level security;
alter table saas.plugin_reviews enable row level security;
alter table saas.plugin_listing_categories enable row level security;

alter table saas.plugin_categories force row level security;
alter table saas.plugin_listings force row level security;
alter table saas.plugin_versions force row level security;
alter table saas.plugin_assets force row level security;
alter table saas.plugin_installs force row level security;
alter table saas.plugin_reviews force row level security;
alter table saas.plugin_listing_categories force row level security;

drop policy if exists plugin_categories_select_all on saas.plugin_categories;
create policy plugin_categories_select_all on saas.plugin_categories
  for select
  using (true);

drop policy if exists plugin_listings_select_visible on saas.plugin_listings;
create policy plugin_listings_select_visible on saas.plugin_listings
  for select
  using (
    (visibility = 'public' and review_status = 'approved')
    or saas.is_member_of_org(organization_id, saas.current_user_id())
  );

drop policy if exists plugin_listings_manage_org on saas.plugin_listings;
create policy plugin_listings_manage_org on saas.plugin_listings
  for all
  using (saas.has_org_role(organization_id, saas.current_user_id(), array['owner', 'admin']))
  with check (saas.has_org_role(organization_id, saas.current_user_id(), array['owner', 'admin']));

drop policy if exists plugin_versions_select_visible on saas.plugin_versions;
create policy plugin_versions_select_visible on saas.plugin_versions
  for select
  using (
    exists (
      select 1
      from saas.plugin_listings l
      where l.id = listing_id
        and (
          (l.visibility = 'public' and l.review_status = 'approved')
          or saas.is_member_of_org(l.organization_id, saas.current_user_id())
        )
    )
  );

drop policy if exists plugin_versions_manage_org on saas.plugin_versions;
create policy plugin_versions_manage_org on saas.plugin_versions
  for all
  using (
    exists (
      select 1
      from saas.plugin_listings l
      where l.id = listing_id
        and saas.has_org_role(l.organization_id, saas.current_user_id(), array['owner', 'admin'])
    )
  )
  with check (
    exists (
      select 1
      from saas.plugin_listings l
      where l.id = listing_id
        and saas.has_org_role(l.organization_id, saas.current_user_id(), array['owner', 'admin'])
    )
  );

drop policy if exists plugin_assets_select_visible on saas.plugin_assets;
create policy plugin_assets_select_visible on saas.plugin_assets
  for select
  using (
    exists (
      select 1
      from saas.plugin_listings l
      where l.id = listing_id
        and (
          (l.visibility = 'public' and l.review_status = 'approved')
          or saas.is_member_of_org(l.organization_id, saas.current_user_id())
        )
    )
  );

drop policy if exists plugin_assets_manage_org on saas.plugin_assets;
create policy plugin_assets_manage_org on saas.plugin_assets
  for all
  using (
    exists (
      select 1
      from saas.plugin_listings l
      where l.id = listing_id
        and saas.has_org_role(l.organization_id, saas.current_user_id(), array['owner', 'admin'])
    )
  )
  with check (
    exists (
      select 1
      from saas.plugin_listings l
      where l.id = listing_id
        and saas.has_org_role(l.organization_id, saas.current_user_id(), array['owner', 'admin'])
    )
  );

drop policy if exists plugin_reviews_select_listing_members on saas.plugin_reviews;
create policy plugin_reviews_select_listing_members on saas.plugin_reviews
  for select
  using (
    exists (
      select 1
      from saas.plugin_listings l
      where l.id = listing_id
        and saas.is_member_of_org(l.organization_id, saas.current_user_id())
    )
  );

drop policy if exists plugin_reviews_insert_listing_managers on saas.plugin_reviews;
create policy plugin_reviews_insert_listing_managers on saas.plugin_reviews
  for insert
  with check (
    exists (
      select 1
      from saas.plugin_listings l
      where l.id = listing_id
        and saas.has_org_role(l.organization_id, saas.current_user_id(), array['owner', 'admin'])
    )
  );

drop policy if exists plugin_installs_select_visible on saas.plugin_installs;
create policy plugin_installs_select_visible on saas.plugin_installs
  for select
  using (
    installed_by_gotrue_id = saas.current_user_id()
    or (organization_id is not null and saas.is_member_of_org(organization_id, saas.current_user_id()))
    or (project_ref is not null and saas.is_member_of_project(project_ref, saas.current_user_id()))
  );

drop policy if exists plugin_installs_insert_visible on saas.plugin_installs;
create policy plugin_installs_insert_visible on saas.plugin_installs
  for insert
  with check (
    saas.current_user_id() is not null
    and (
      installed_by_gotrue_id = saas.current_user_id()
      or (organization_id is not null and saas.is_member_of_org(organization_id, saas.current_user_id()))
      or (project_ref is not null and saas.is_member_of_project(project_ref, saas.current_user_id()))
    )
  );

drop policy if exists plugin_installs_update_visible on saas.plugin_installs;
create policy plugin_installs_update_visible on saas.plugin_installs
  for update
  using (
    installed_by_gotrue_id = saas.current_user_id()
    or (organization_id is not null and saas.is_member_of_org(organization_id, saas.current_user_id()))
    or (project_ref is not null and saas.is_member_of_project(project_ref, saas.current_user_id()))
  )
  with check (
    installed_by_gotrue_id = saas.current_user_id()
    or (organization_id is not null and saas.is_member_of_org(organization_id, saas.current_user_id()))
    or (project_ref is not null and saas.is_member_of_project(project_ref, saas.current_user_id()))
  );

drop policy if exists plugin_listing_categories_select_visible on saas.plugin_listing_categories;
create policy plugin_listing_categories_select_visible on saas.plugin_listing_categories
  for select
  using (
    exists (
      select 1
      from saas.plugin_listings l
      where l.id = listing_id
        and (
          (l.visibility = 'public' and l.review_status = 'approved')
          or saas.is_member_of_org(l.organization_id, saas.current_user_id())
        )
    )
  );

drop policy if exists plugin_listing_categories_manage_org on saas.plugin_listing_categories;
create policy plugin_listing_categories_manage_org on saas.plugin_listing_categories
  for all
  using (
    exists (
      select 1
      from saas.plugin_listings l
      where l.id = listing_id
        and saas.has_org_role(l.organization_id, saas.current_user_id(), array['owner', 'admin'])
    )
  )
  with check (
    exists (
      select 1
      from saas.plugin_listings l
      where l.id = listing_id
        and saas.has_org_role(l.organization_id, saas.current_user_id(), array['owner', 'admin'])
    )
  );

revoke all on saas.plugin_categories from public;
revoke all on saas.plugin_listings from public;
revoke all on saas.plugin_versions from public;
revoke all on saas.plugin_assets from public;
revoke all on saas.plugin_installs from public;
revoke all on saas.plugin_reviews from public;
revoke all on saas.plugin_listing_categories from public;

grant select on saas.plugin_categories to postgres, authenticated, service_role;
grant select, insert, update, delete on saas.plugin_listings to postgres, authenticated, service_role;
grant select, insert, update, delete on saas.plugin_versions to postgres, authenticated, service_role;
grant select, insert, update, delete on saas.plugin_assets to postgres, authenticated, service_role;
grant select, insert, update, delete on saas.plugin_installs to postgres, authenticated, service_role;
grant select, insert, update, delete on saas.plugin_reviews to postgres, authenticated, service_role;
grant select, insert, update, delete on saas.plugin_listing_categories to postgres, authenticated, service_role;

alter table saas.plugin_categories owner to postgres;
alter table saas.plugin_listings owner to postgres;
alter table saas.plugin_versions owner to postgres;
alter table saas.plugin_assets owner to postgres;
alter table saas.plugin_installs owner to postgres;
alter table saas.plugin_reviews owner to postgres;
alter table saas.plugin_listing_categories owner to postgres;
